<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Actuator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reading"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandStatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLog"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entry"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleHierarchy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Owner"/>
  <eClassifiers xsi:type="ecore:EClass" name="SHAS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Here"/>
  <eClassifiers xsi:type="ecore:EClass" name="This"/>
</ecore:EPackage>
