<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Attendee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attendanceStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occasion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventKind" eType="#//EventKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" eType="#//Organizer" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Location" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type_of" eType="#//EventKind" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Checklist" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has_invitations" eType="#//Invitation" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checklist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" eType="#//Task" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" eType="#//Task" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignedToAttendee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigned_to" eType="#//Attendee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invitation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee" eType="#//Attendee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sent_to" eType="#//Attendee" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//firstName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="firstName"/>
  <eClassifiers xsi:type="ecore:EClass" name="lastName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//email"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="email"/>
  <eClassifiers xsi:type="ecore:EClass" name="postalAddress">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//phoneNumber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="phoneNumber"/>
  <eClassifiers xsi:type="ecore:EClass" name="password">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Boolean" eType="#//isAttending"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="isAttending"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organizer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizes" eType="#//Event" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
