<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Organizer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attendee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Checklist"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCategory"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invitation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Here"/>
  <eClassifiers xsi:type="ecore:EClass" name="cloud"/>
</ecore:EPackage>
