<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookings" eType="#//Booking" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Booking">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" eType="#//JourneySegment" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTrip" eType="#//Trip" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JourneySegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedCabin" eType="#//Cabin" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cabin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trip"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedBookings" eType="#//Booking" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedCabin" eType="#//Cabin" upperBound="-1" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
