<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedRooms" eType="#//Room" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedSensors" eType="#//SensorDevice" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedActuators" eType="#//ActuatorDevice" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBy" eType="#//User" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReadings" eType="#//SensorReading" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedCommands" eType="#//ControlCommand" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" eType="#//SmartHome" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedRooms" eType="#//Room" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
