<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" eType="#//Device" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" eType="#//AutomationRule" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" eType="#//Device" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" eType="#//AutomationRule" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readings" eType="#//SensorReading" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedCommands" eType="#//ControlCommand" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlCommand" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" eType="#//ControlCommand" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
