<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedDevices" eType="#//Device" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReadings" eType="#//SensorReading" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedCommands" eType="#//ControlCommand" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRules" eType="#//AutomationRule" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule"/>
</ecore:EPackage>
