<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directedFilms" eType="#//Film" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Technician" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilmSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedFilms" eType="#//Film" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Film">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOnScript" eType="#//Screenplay" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptedFrom" eType="#//Screenplay" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="directedBy" eType="#//Director" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screenplay">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inspiredBy" eType="#//Novel" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Novel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Screenwriter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authoredScripts" eType="#//Screenplay" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenFor" eType="#//Film" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreativeEmployee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directedFilms" eType="#//Film" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writtenScripts" eType="#//Screenplay" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedIn" eType="#//Film" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
