<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performed" eType="#//Repair" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repair"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigned" eType="#//Order" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongs_to" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placed_by" eType="#//PartnerCompany"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigned_by" eType="#//Planner" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executed_by" eType="#//Driver" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" eType="#//Vehicle" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PartnerCompany"/>
  <eClassifiers xsi:type="ecore:EClass" name="Planner"/>
  <eClassifiers xsi:type="ecore:EClass" name="Driver"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" eType="#//Repair" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
