<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="DriveSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Motor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Battery"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicController"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdvancedController"/>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Frame" eType="#//frame" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="frame"/>
  <eClassifiers xsi:type="ecore:EClass" name="driveSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Controller" eType="#//controller"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="battery"/>
  <eClassifiers xsi:type="ecore:EClass" name="class"/>
</ecore:EPackage>
