<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observingHistory" eType="#//Observation" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStateEnvelope" eType="#//Envelope" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learnedPolicy" eType="#//Policy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStateVector" eType="#//StateVector" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Envelope"/>
  <eClassifiers xsi:type="ecore:EClass" name="Policy"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrainingSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedObservations" eType="#//Observation" lowerBound="1" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="watchedAgents" eType="#//Agent" lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedRewards" eType="#//RewardStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RewardStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedRewards" eType="#//RewardStructure" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimizedPolicy" eType="#//Policy" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledSession" eType="#//TrainingSession" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVector"/>
</ecore:EPackage>
