@startuml
    class Diagram {
        "System Requirement" as systemRequirement

        systemRequirement
            node {systemRequirement}
    }

    systemRequirement
        ---> [systemRequirement]

@enduml
