<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedTrajectories" eType="#//Trajectory" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trajectory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedBuses" eType="#//Bus" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubscriptionRequest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestingCustomer" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedPaymentMethod" eType="#//PaymentMethod" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedAddresses" eType="#//Address" lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldCards" eType="#//MENSOCard" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="Address"/>
  <eClassifiers xsi:type="ecore:EClass" name="MENSOCard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedForTrips" eType="#//TripRecord" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TripRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelledLine" eType="#//BusLine" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoicedCustomer" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredTrips" eType="#//TripRecord" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedPayment" eType="#//PaymentMethod" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAggregationEngine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedRecords" eType="#//TripRecord" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApprovalAuthority">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluatedTrajectories" eType="#//Trajectory" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvoicingService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedInvoices" eType="#//Invoice" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
