<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderedProduct" eType="#//ProductItem" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturer" eType="#//Manufacturer" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manufacturer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionBatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="temporaryLocation" eType="#//WarehouseLocation" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturedProduct" eType="#//ProductItem" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WarehouseLocation"/>
</ecore:EPackage>
