@startuml

class diagram: System Requirements

part1: Component 1
   class component1 : Component {
      attribute name : String
      attribute type : String
   }

part2: Component 2
   class component2 : Component {
      attribute name : String
      attribute type : String
   }

part3: Component 3
   class component3 : Component {
      attribute name : String
      attribute type : String
   }

part4: Component 4
   class component4 : Component {
      attribute name : String
      attribute type : String
   }

part5: Component 5
   class component5 : Component {
      attribute name : String
      attribute type : String
   }

part6: Component 6
   class component6 : Component {
      attribute name : String
      attribute type : String
   }

part7: Component 7
   class component7 : Component {
      attribute name : String
      attribute type : String
   }

part8: Component 8
   class component8 : Component {
      attribute name : String
      attribute type : String
   }

part9: Component 9
   class component9 : Component {
      attribute name : String
      attribute type : String
   }

part10: Component 10
   class component10 : Component {
      attribute name : String
      attribute type : String
   }

@enduml
