<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedRooms" eType="#//MeetingRoom" lowerBound="2" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeetingRoom"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceRoom" eType="#//Room" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedEvents" eType="#//HostedEvent" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedModerators" eType="#//Moderator" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostedEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Moderator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedSessions" eType="#//ConferenceSession" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conductedRegistrations" eType="#//Registration" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintainedRooms" eType="#//Room" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegatingUsers" eType="#//User" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Registration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredSession" eType="#//ConferenceSession" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatedSessions" eType="#//ConferenceSession" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
