<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abilityAssessment" eType="#//StayAbilityAssessment" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StayAbilityAssessment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inhabitant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ongoingProposal" eType="#//Proposal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outstandingInvoices" eType="#//Invoice" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pendingIn" eType="#//WaitingList" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetInhabitant" eType="#//Person" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDepartment" eType="#//Department" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitingList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposals" eType="#//Proposal" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stays" eType="#//Stay" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stay">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedBed" eType="#//Bed" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="housingDepartment" eType="#//Department" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bed"/>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beds" eType="#//Bed" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="payments" eType="#//PaymentRecord" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credits" eType="#//CreditNote" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredStay" eType="#//Stay" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentRecord"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreditNote"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvoiceManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedInvoices" eType="#//Invoice" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
