<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelRecords" eType="#//RefuelingRecord" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefuelingRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//Invoice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedPump" eType="#//Pump" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="issuedFrom" eType="#//GasStation" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices" eType="#//Invoice" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="homeStation" eType="#//GasStation" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GasStation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pumps" eType="#//Pump" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pump"/>
</ecore:EPackage>
