<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedReadings" eType="#//SensorReading" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAggregator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedLogs" eType="#//LogEntry" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trendReport" eType="#//TrendAnalysis" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedRules" eType="#//AlertRule" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrendAnalysis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedLogs" eType="#//LogEntry" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlertRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluatedLogs" eType="#//LogEntry" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlertManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedRules" eType="#//AlertRule" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredLogs" eType="#//LogEntry" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//SystemState" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectedReadings" eType="#//SensorReading" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
