<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPolicies" eType="#//PolicyDocument" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedClaims" eType="#//Claim" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Claim">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conductedHearing" eType="#//Hearing" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hearing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingParticipants" eType="#//HearingParticipant" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concludedResults" eType="#//HearingResult" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HearingParticipant"/>
  <eClassifiers xsi:type="ecore:EClass" name="HearingResult"/>
</ecore:EPackage>
