@startuml
    class Diagram {
        [Start]
        start: "System Requirement" with
            "System Requirement" as name,
            "System Requirement" as description,
            "System Requirement" as author,
            "System Requirement" as version,
            "System Requirement" as priority,
            "System Requirement" as date
    }

    end
@enduml
