<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deck"/>
  <eClassifiers xsi:type="ecore:EClass" name="Card"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Suit"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparison"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScoringTable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Round"/>
  <eClassifiers xsi:type="ecore:EClass" name="JackRound"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoloRound"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatorySoloRound"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SoloType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Here"/>
  <eClassifiers xsi:type="ecore:EClass" name="It"/>
</ecore:EPackage>
