<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Owner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredCars" eType="#//Car" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" eType="#//Car" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rideShareBookings" eType="#//RideShareBooking" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rideHailBookings" eType="#//RideHailBooking" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booked" eType="#//RideHailBooking" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booked" eType="#//RideShareBooking" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RideService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pickupTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dropoffTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pickupLocation" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dropoffLocation" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rideDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RideHailBooking" eSuperTypes="#//RideService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestType" eType="#//RequestType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadCustomer" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RideShareBooking" eSuperTypes="#//RideService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negotiatedFee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customerList" eType="#//Customer" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treesPlanted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accident">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accidentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestType">
    <eLiterals xsi:type="ecore:EEnumLiteral" name="APP"/>
    <eLiterals xsi:type="ecore:EEnumLiteral" name="HAND_WAVING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="```plantuml" eType="#//This" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="This"/>
  <eClassifiers xsi:type="ecore:EClass" name="startuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//carId" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="carId"/>
  <eClassifiers xsi:type="ecore:EClass" name="licensePlate"/>
  <eClassifiers xsi:type="ecore:EClass" name="wner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" eType="#//licensePlate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="isSelfDriving">
    <eStructuralFeatures xsi:type="ecore:EReference" name="List&lt;Accident&gt;" eType="#//accidents" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="accidents"/>
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Accident" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
