<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentDeck" eType="#//Deck" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deck"/>
  <eClassifiers xsi:type="ecore:EClass" name="GameSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoringTable" eType="#//ScoringTable" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" eType="#//Player" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" eType="#//Match" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoringTable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hand" eType="#//Card" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rounds" eType="#//Round" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Round">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" eType="#//Player" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="winningCard" eType="#//Card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card"/>
</ecore:EPackage>
