@startuml

class Diagram {
    class SystemRequirement {
        # system requirement
    }

        classDiagram
            user -> SystemRequirement { system requirement }
    }

@enduml
