<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaffMember" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentNotifications" eType="#//Notification" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineItems" eType="#//OrderLine" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedDriver" eType="#//Employee" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedVehicle" eType="#//Vehicle" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceHistory" eType="#//MaintenanceLog" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notification"/>
  <eClassifiers xsi:type="ecore:EClass" name="DispatchPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedOrders" eType="#//Order" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceLog"/>
</ecore:EPackage>
