<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml" eSuperTypes="#//FlightTerminal"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlightTerminal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flight" eSuperTypes="#//TransportationMode #//Traveler"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransportationMode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Traveler"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reservation" eSuperTypes="#//Passenger"/>
  <eClassifiers xsi:type="ecore:EClass" name="Passenger"/>
  <eClassifiers xsi:type="ecore:EClass" name="BreakdownData" eSuperTypes="#//Flight"/>
</ecore:EPackage>
