<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedResponses" eType="#//InterventionResponse" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterventionResponse"/>
  <eClassifiers xsi:type="ecore:EClass" name="HotlineCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originatingPoint" eType="#//ContactPoint" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContactPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyAdvisor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorizedCalls" eType="#//HotlineCall" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcedCall" eType="#//HotlineCall" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportingAssessment" eType="#//RiskAssessment" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiskAssessment"/>
</ecore:EPackage>
