<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceTasks" eType="#//MaintenanceTask" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredSchedule" eType="#//CleaningSchedule" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedRecord" eType="#//RepairRecord" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloorSurface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairServices" eType="#//RepairService" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepairService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handledTasks" eType="#//MaintenanceTask" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsRecords" eType="#//RepairRecord" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiresMaterial" eType="#//CleaningMaterial" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedMaterials" eType="#//CleaningMaterial" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredConfigurations" eType="#//EquipmentConfig" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepairRecord"/>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningMaterial"/>
  <eClassifiers xsi:type="ecore:EClass" name="EquipmentConfig"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenancePlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="focusesOnSurfaces" eType="#//FloorSurface" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InventoryMonitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trackedMaterials" eType="#//CleaningMaterial" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepairLog"/>
</ecore:EPackage>
