<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSlots" eType="#//PerformanceSlot" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedInstrument" eType="#//Instrument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instrument"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedPerformances" eType="#//Performance" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Performance"/>
</ecore:EPackage>
