<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedBroker" eType="#//Broker" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Broker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handledClaims" eType="#//Claim" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPolicies" eType="#//InsurancePolicy" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsurancePolicy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Claim">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedDocuments" eType="#//Document" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReports" eType="#//AssessmentReport" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentReport"/>
  <eClassifiers xsi:type="ecore:EClass" name="Estimator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessedClaims" eType="#//Claim" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
