<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="DesignatedPlayerProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playerAttributes" eType="#//map"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongListEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileMatch" eType="#//DesignatedPlayerProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoutingAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" eType="#//Scout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoutingReport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pros" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cons" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recommendation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShortListEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designatedProfile" eType="#//DesignatedPlayerProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClubEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeadCoach" eSuperTypes="#//ClubEmployee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//ClubEmployee"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeadScout" eSuperTypes="#//ClubEmployee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scout" eSuperTypes="#//ClubEmployee"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="int" eType="#//id" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="id"/>
  <eClassifiers xsi:type="ecore:EClass" name="name">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//position"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="position"/>
  <eClassifiers xsi:type="ecore:EClass" name="map"/>
  <eClassifiers xsi:type="ecore:EClass" name="Player"/>
</ecore:EPackage>
