<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfFaculties" eType="#//Faculty" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfInstitutes" eType="#//Institute" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Institute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employsMembers" eType="#//Employee" lowerBound="1" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatedInProjects" eType="#//Project" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taughtCourses" eType="#//Course" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project"/>
  <eClassifiers xsi:type="ecore:EClass" name="Course"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResearchAssistant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affiliatedWith" eType="#//Institute" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer"/>
  <eClassifiers xsi:type="ecore:EClass" name="University"/>
</ecore:EPackage>
