<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" eType="#//Card" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//RefuelTurn" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefuelTurn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" eType="#//InvoiceItem" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvoiceItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" eType="#//InvoiceItem" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receives" eType="#//Payment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gets" eType="#//Invoice" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GasStation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Pump" lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" eType="#//DailyReport" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pump">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" eType="#//GasType" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//RefuelTurn" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongs_to" eType="#//GasStation" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GasType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DailyReport"/>
</ecore:EPackage>
