<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="medicalHistory" eType="#//DiagnosticReport" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticReport"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" eType="#//Patient" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recordedEvents" eType="#//PainEvent" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReport" eType="#//DiagnosticReport" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patient"/>
  <eClassifiers xsi:type="ecore:EClass" name="PainEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="MedicalDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReports" eType="#//DiagnosticReport" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
