<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="voyagePaths" eType="#//VoyagePath" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoyagePath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelRunways" eType="#//FuelRunway" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupedPassengers" eType="#//PassengerGroup" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelRunway"/>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerGroup"/>
</ecore:EPackage>
