<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" eType="#//SensorDevice" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" eType="#//Measurement" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measurement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedApartment" eType="#//Apartment" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedAlerts" eType="#//AlertMessage" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Apartment"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMonitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredController" eType="#//SensorController" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlertMessage"/>
</ecore:EPackage>
