<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageMap" eType="#//CoverageMap" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedSensors" eType="#//Sensor" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitoringZone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSensors" eType="#//Sensor" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFeed" eType="#//TelemetryFeed" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="TelemetryFeed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedPackets" eType="#//DataPacket" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceZone" eType="#//MonitoringZone" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPacket"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSeriesRecord"/>
</ecore:EPackage>
