<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leasePurchased" eType="#//PropertyUnit" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeaseAgreement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="amendmentRequests" eType="#//AdjustmentRequest" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorizedReader" eType="#//Reader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auditHistory" eType="#//AuditLog" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pricingUnit" eType="#//PricingUnit" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdjustmentRequest"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervisedAgreements" eType="#//LeaseAgreement" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuditLog"/>
  <eClassifiers xsi:type="ecore:EClass" name="PricingUnit"/>
</ecore:EPackage>
