<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="madeTransactions" eType="#//PaymentTransaction" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentTransaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingGateway" eType="#//PaymentGateway" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAccount" eType="#//BankAccount" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingEngine" eType="#//PaymentProcessor" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentGateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="BankAccount"/>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentProcessor"/>
</ecore:EPackage>
