@startuml

class SystemRequirement {
    member {System Requirement}
}

        component "System Requirement" {
            class SystemRequirement {
                member {System Requirement}
            }
        }
    }
}

@enduml
