<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isOwner" eType="#//Game" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definesBlocks" eType="#//Block" lowerBound="1" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//HallOfFame" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedSessions" eType="#//PlaySession" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownsSessions" eType="#//PlaySession" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaySession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactsWithBlocks" eType="#//Block" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playsAs" eType="#//User" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="HallOfFame">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsEntries" eType="#//ScoreEntry" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoreEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoredBy" eType="#//User" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
