<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedToSegment" eType="#//NetworkSegment" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkSegment"/>
  <eClassifiers xsi:type="ecore:EClass" name="AccessNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recordedTransitions" eType="#//TrafficData" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrafficData"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrafficAnalyzer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedSegments" eType="#//NetworkSegment" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedData" eType="#//TrafficData" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemMonitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredNodes" eType="#//AccessNode" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
