<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedEvents" eType="#//Event" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guestList" eType="#//GuestList" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checklist" eType="#//EventChecklist" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitations" eType="#//Invitation" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuestList"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventChecklist"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invitation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipient" eType="#//Attendee" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedEvent" eType="#//Event" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attendee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendedEvents" eType="#//Event" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTasks" eType="#//Task" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organizer"/>
</ecore:EPackage>
