<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeSessions" eType="#//Session" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session"/>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentNotifications" eType="#//Notification" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loggedActivities" eType="#//ActivityLog" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipient" eType="#//User" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentToServer" eType="#//CloudServer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedNotifications" eType="#//Notification" lowerBound="1" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveredNotifications" eType="#//Notification" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredCompanions" eType="#//User" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetServer" eType="#//CloudServer" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudServer"/>
</ecore:EPackage>
