<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attractions" eType="#//TouristAttraction" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TouristAttraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizedTours" eType="#//GuidedTour" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuidedTour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadGuide" eType="#//Guide" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" eType="#//Visitor" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guide"/>
  <eClassifiers xsi:type="ecore:EClass" name="Visitor"/>
</ecore:EPackage>
