<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" eType="#//Attraction" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offers" eType="#//GuidedTour" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="City">
    <eStructuralFeatures xsi:type="ecore:EReference" name="residents" eType="#//Visitor" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GuidedTour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joins" eType="#//Visitor" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Booking">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" eType="#//GuidedTour" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" eType="#//Visitor" upperBound="-1" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
