<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="designedBoard" eType="#//GameBoard" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameBoard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedTiles" eType="#//GameTile" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameDesigner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedMode" eType="#//GameMode" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdDeck" eType="#//ActionDeck" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameMode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionDeck"/>
  <eClassifiers xsi:type="ecore:EClass" name="GameTile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedPieces" eType="#//ConnectionPiece" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPiece"/>
  <eClassifiers xsi:type="ecore:EClass" name="GameSession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeBoard" eType="#//GameBoard" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeDeck" eType="#//ActionDeck" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeMode" eType="#//GameMode" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingPlayers" eType="#//Player" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="occupiedTiles" eType="#//GameTile" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originatingPlayer" eType="#//Player" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="landingTile" eType="#//GameTile" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
