@startuml
classDiagram

systemRequirement --> requirement1 {
    systemRequirement has relation to requirement1
}

requirement1 --> component1 {
    requirement1 has relation to component1
}
component1 --> component2 {
    component1 has relation to component2
}
component2 --> component3 {
    component2 has relation to component3
}
component3 --> systemRequirement {
    component3 has relation to systemRequirement
}
@enduml
