<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedRecord" eType="#//TrainingRecord" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainingRecord"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabStaff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedChecks" eType="#//SafetyCheck" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedSources" eType="#//RadiationSource" lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learnerRecords" eType="#//TrainingRecord" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyCheck">
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkedSource" eType="#//RadiationSource" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadiationSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adheringStandard" eType="#//EnvironmentalStandard" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compatibleFillers" eType="#//Filler" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalStandard"/>
  <eClassifiers xsi:type="ecore:EClass" name="Filler"/>
</ecore:EPackage>
