<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vatNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploads" eType="#//Upload" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegularUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseHistory" eType="#//Purchase" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedAlbums" eType="#//Album" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buys" eType="#//Purchase" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Purchase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="song" eType="#//Song"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//RegularUser"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purchaseDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buyer" eType="#//RegularUser" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchased_song" eType="#//Single" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trackList" eType="#//Hit" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedToUsers" eType="#//RegularUser" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" eType="#//Hit" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggested_to" eType="#//RegularUser" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Upload">
    <eStructuralFeatures xsi:type="ecore:EReference" name="song" eType="#//Song"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessUser" eType="#//BusinessUser"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//Song"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hit" eSuperTypes="#//Song">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part_of" eType="#//Album" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//title" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="title"/>
  <eClassifiers xsi:type="ecore:EClass" name="year">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//genre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="genre"/>
  <eClassifiers xsi:type="ecore:EClass" name="getUniqueKey"/>
  <eClassifiers xsi:type="ecore:EClass" name="name">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String_" eType="#//getUniqueKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dateOfBirth">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//websiteURL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="websiteURL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongs_to" eType="#//Artist" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uploaded_via" eType="#//Upload" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="creates" eType="#//Song" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
