@startuml
classDiagram
    user -> systemRequirement

systemRequirement --> class Diagram1
    Diagram1 has classDiagram2, diagram3
    diagram3 has classDiagram4, diagram5
    classDiagram4 has classDiagram6, classDiagram7
    classDiagram6 has classDiagram8
    classDiagram7 has classDiagram9
@enduml
