<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" eType="#//OrderItem" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedDeliveryAddress" eType="#//DeliveryAddress" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Customer" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesProfile" eType="#//DeliveryProfile" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedCategory" eType="#//ProductCategory" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliveryAddress"/>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" eType="#//ShoppingPreference" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPendingRequests" eType="#//ReservationRequest" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliveryProfile"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductCategory"/>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPickupAddress" eType="#//DeliveryAddress"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adoptedHeader" eType="#//DeliveryProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShoppingPreference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReservationRequest"/>
</ecore:EPackage>
