<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledMaintenance" eType="#//MaintenanceSchedule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plannedTasks" eType="#//RepairTask" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCategory" eType="#//VehicleCategory" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Person" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeSegments" eType="#//RouteSegment" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VehicleCategory"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepairTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouteSegment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Depot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedVehicles" eType="#//Vehicle" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" eType="#//RouteSegment" upperBound="-1" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
