<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryAccount" eType="#//UserAccount" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserAccount"/>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAccounts" eType="#//SystemAccount" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemAccount">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedFolders" eType="#//Folder" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribers" eType="#//User" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//FileItem" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" eType="#//Workflow" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" eType="#//Task" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetItem" eType="#//FileItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedLevels" eType="#//PriorityLevel" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="approvers" eType="#//SystemAccount" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PriorityLevel"/>
</ecore:EPackage>
