<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forestTrees" eType="#//ForestTree" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForestTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="historicalObservations" eType="#//TreeObservation" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="climateReport" eType="#//ClimateReport" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weatherRecords" eType="#//WeatherData" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeObservation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClimateReport"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeatherData"/>
  <eClassifiers xsi:type="ecore:EClass" name="MonitoringStation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredTrees" eType="#//ForestTree" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainTarget" eType="#//ForestTree" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
