<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryStorage" eType="#//StorageBin" lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageBin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recordedReadings" eType="#//SensorReading" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Warehouse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredStations" eType="#//MonitoringStation" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitoringStation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectedReadings" eType="#//SensorReading" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedReports" eType="#//AnomalyReport" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticsEngine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredWarehouse" eType="#//Warehouse" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnomalyReport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredEvent" eType="#//SafetyEvent" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEngine" eType="#//DiagnosticsEngine" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
