<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="SeatCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasEntertainment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSeats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flightNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" eType="#//Passenger" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Ticket" lowerBound="1" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crew" eType="#//FlightAttendant" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="captain" eType="#//Pilot" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="co-pilots" eType="#//Pilot" upperBound="2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departure" eType="#//Airport" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//Airport" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Passenger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passportNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wantsUpgrade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongs_to" eType="#//SeatCategory" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employs" eType="#//FlightAttendant" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employs" eType="#//Pilot" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlightAttendant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employmentDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isChiefSteward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pilot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employmentDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Airport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRunways" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Here">
    <eStructuralFeatures xsi:type="ecore:EReference" name="String" eType="#//name" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="name"/>
  <eClassifiers xsi:type="ecore:EClass" name="type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="int" eType="#//yearOfManufacture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="yearOfManufacture"/>
  <eClassifiers xsi:type="ecore:EClass" name="nextInspectionDate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="int" eType="#//numberOfSeats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="numberOfSeats"/>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerAircraft" eSuperTypes="#//Aircraft">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//SeatCategory" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aircraft">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" eType="#//Flight" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part_of" eType="#//Airline" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="home_airport" eType="#//Airport" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
