<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="generated" nsURI="http://www.example.org/generated" nsPrefix="generated" xmi:version="2.0">
  <eClassifiers xsi:type="ecore:EClass" name="plantuml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" eType="#//GamificationEvent" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamificationEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="streams" eType="#//GameStream" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phase" eType="#//GamePhase" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameStream"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceStream" eType="#//GameStream" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" eType="#//Player" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="GamePhase"/>
</ecore:EPackage>
